#!/bin/sh

alias jsc=/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/Resources/jsc

JSHINT_PATH="`dirname "$0"`"
CONFIG_PATH="$HOME/.jshint/config.js"
CONFIG="`cat $CONFIG_PATH`"

echo $CONFIG

if test -z $CONFIG; then
    jsc "$JSHINT_PATH/jshint.js" "$JSHINT_PATH/jshint.jsc.js" -- "`cat $1`"
else
    jsc "$JSHINT_PATH/jshint.js" "$JSHINT_PATH/jshint.jsc.js" -- "`cat $1`" "$CONFIG"
fi
